import test from 'node:test';
import assert from 'node:assert/strict';
import {scanRoomMembers} from '../src/member-scanner.mjs';
const node=(shortId,text='',x=20,y=700,x2=500,y2=750,extra={})=>({shortId,text,x,y,x2,y2,centerX:(x+x2)/2,centerY:(y+y2)/2,...extra});
const header=[node('layout_online_user','',800,100,1050,200,{clickable:true})];
const popup=(rows=[],count=3)=>[node('tvTitle',`房间在线用户(${count}人)`),node('ivBack','',10,500,80,600,{clickable:true}),node('mRecyclerView','',0,653,1080,1920),...rows];
function mock(frames){let i=0;const taps=[],swipes=[];return {taps,swipes,bridge:{dumpUi:async()=>({nodes:frames[Math.min(i++,frames.length-1)]}),tapByCoord:async(...args)=>{taps.push(args);return {ok:true};}},adb:{swipe:async(...args)=>swipes.push(args)}};}
test('opens observed online entry, reports empty and closes verified popup',async()=>{const d=mock([header,popup([node('tv_message','暂无数据')],0)]);let logs=[];const r=await scanRoomMembers(d,{onLog:(_l,m)=>logs.push(m)});assert.equal(r.status,'empty');assert.equal(r.advertisedCount,0);assert.equal(r.users.length,0);assert.equal(d.taps.length,2);assert.equal(d.swipes.length,0);assert.ok(logs.some(m=>m.includes('公屏')));});
test('walks bounded list, overlaps swipes, deduplicates and keeps unpaired names unverified',async()=>{const a=[node('tv_nickname','A'),node('tv_user_code','12345',600,705,900,745)];const b=[...a,node('nickname','B',20,900,500,950)];const d=mock([header,popup(a),popup(b),popup(b)]);const batches=[];const r=await scanRoomMembers(d,{maxPages:5,onUsers:u=>batches.push(u)});assert.equal(r.status,'partial');assert.equal(r.reason,'no_progress');assert.equal(r.users.length,2);assert.equal(r.users[0].uid,'12345');assert.equal(r.users[1].uidReal,false);assert.equal(batches.flat().length,2);assert.ok(d.swipes.every(s=>s[1]<1920&&s[3]>653&&s[1]>s[3]));});
test('ambiguous nickname-to-ID geometry does not manufacture verified identities',async()=>{const d=mock([header,popup([node('nickname','A'),node('nickname','B'),node('tv_nice_num','12345',600,705,900,745)])]);const r=await scanRoomMembers(d,{maxPages:1});assert.ok(r.users.every(u=>u.uidReal===false));assert.equal(r.status,'partial');assert.equal(r.reason,'max_pages');});
test('foreign app and invalid entries are never clicked',async()=>{for(const nodes of [[...header,node('x','',0,0,1,1,{packageName:'other.app'})],[node('layout_online_user','',0,0,0,0,{clickable:true})]]){const d=mock([nodes]);const r=await scanRoomMembers(d);assert.equal(r.status,'unavailable');assert.equal(d.taps.length,0);}});
test('cancellation prevents scan clicks',async()=>{const c=new AbortController();c.abort();const d=mock([header]);await assert.rejects(scanRoomMembers(d,{signal:c.signal}),{name:'AbortError'});assert.equal(d.taps.length,0);});
test('does not blindly close unknown page after entry navigation fails',async()=>{const d=mock([header,[]]);const r=await scanRoomMembers(d,{maxDurationMs:40});assert.equal(r.status,'unavailable');assert.equal(d.taps.length,1);});
test('a late cancelled snapshot does not publish users or perform more device actions',async()=>{const c=new AbortController();const d=mock([header]);let reads=0,published=0;d.bridge.dumpUi=async()=>{reads++;if(reads===2){c.abort();return {nodes:popup([node('nickname','A')])};}return {nodes:header};};await assert.rejects(scanRoomMembers(d,{signal:c.signal,onUsers:()=>published++}),{name:'AbortError'});assert.equal(published,0);assert.equal(d.taps.length,1);assert.equal(d.swipes.length,0);assert.equal(reads,2);});
test('changing app after a popup read never triggers a blind back click',async()=>{const d=mock([header,popup([node('nickname','A')]),[node('x','',0,0,1,1,{packageName:'other.app'})]]);const r=await scanRoomMembers(d,{maxPages:1});assert.equal(r.status,'partial');assert.equal(d.taps.length,1);});
